### PR TITLE
Fixed the overflow issue 

### PR DESCRIPTION
**Pull request by kunal-iitj**
- There was an overflow when the app is used in landscape mode
- Explained this problem in detail in an issue.

### CODE REVIEW

**Review by NishantSinghal19 — COMMENTED** [review]
Made this app according to a portrait but didn't check in Landscape mode 
Also, you have only done in Home Screen 
have you tested on the other dialog boxes on other pages if yes then comment yes and I will merge it

**Comment by kunal-iitj** [comment]
There is an overflow somewhere else as well
Could you merge this I will make a separate PR for the other one.

**Comment by kunal-iitj** [comment]
@NishantSinghal19 I have made all the necessary changes across all pages.  If you want any changes please let me know

**Review by NishantSinghal19 — COMMENTED** [review]
Code Checked and is running properly

**Pull request merged**
