### PR TITLE
the application is running on iOS and overflow is resolved in case of…

### PR DESCRIPTION
**Pull request by nikkivirtuoso**
Earlier the code was unable to build executables file for  the app to run on iOS there are package updations in the file like cocoapods and there was string overflow in iOS in profile sections i am sharing the screenshots for the issues and i have resolved these issues
Screenshot 2024-01-04 at 1 52 35 PM
before updation
Screenshot 2024-01-04 at 1 53 14 PM
after updation 
now in android and iOS both are running without any problem

issue : #233

### CODE REVIEW

**Comment by Pavel401** [comment]
@nikkivirtuoso Please mention the issue or create a new  issue .

**Comment by nikkivirtuoso** [comment]
done created

**Comment by nikkivirtuoso** [comment]
now this means i have to submit my PR through that issue ?

**Comment by Pavel401** [comment]
issue : #233

**Pull request merged**
