### PR TITLE
feat: Improve tags add ux while adding task

### LINKED ISSUE #398: feat: Improving ux for adding tags while adding task
### Describe your improvement idea or feature request

After adding tags which has whitespace in between are not valid as per guidelines so after clicking on add task it shows an error snackbar.
It should be changed so that user will not have to delete tags and add differently without space.

### How would you like to see it implemented?

I propose to change this to 
1. while `addTag` we should split the input by whitespaces and add tags differently
2. while input change in `TextFormField` it should check if it ends with `whitespace`, if it, it should add the tag immediately but not if it has white space in between (not in end or start).

### Put here any screenshots or videos (optional)

Error show after adding of tags

### How can we contact you (optional)

Gh: @SGI-CAPP-AT2
Slack: shubham ingale

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

### PR DESCRIPTION
**Pull request by SGI-CAPP-AT2**
# Description

This PR improves the way tags can be added while adding tasks
1. on inputing whitespace tag gets added
2. if input has space in between, it adds the tags by splitting with whitespace
3. also if tags are being repeated it'll delete the tag which was added previously and add again to show that it's added now

## Screenshots

https://github.com/user-attachments/assets/82dda543-6565-42c7-bc96-e00517b5d80e

## Checklist

- [x] Code follows the established coding style guidelines
- [x] All tests are passing
- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes

### CODE REVIEW

**Comment by SGI-CAPP-AT2** [comment]
@BrawlerXull This PR is ready to review

**Comment by BrawlerXull** [comment]
This is not the correct approach for tags as if a person wants to add a tag `Office work` or `Pending rentals` he wont be able to do it as it will be parsed directly in 4 tags according to your proposed approach.

**Comment by SGI-CAPP-AT2** [comment]
@BrawlerXull, 
Yes but the tags which has spaces in between are not supported by taskwarrior
image
It shows above error
so to uses tags like that user must use `-` or `_` 
like `Office-work` or `Pending-rentals`

**Comment by BrawlerXull** [comment]
> @BrawlerXull, Yes but the tags which has spaces in between are not supported by taskwarrior image It shows above error so to use tags like that user must use `-` or `_` like `Office-work` or `Pending-rentals`

Yup my bad

**Review by Pavel401 — APPROVED** [review]
Tested and working fine. Merging this. Thanks, @SGI-CAPP-AT2

**Comment by linuxcaffe** [comment]
Excellent 👍

**Pull request merged**
