### PR TITLE
Add task theme change fix

### LINKED ISSUE #204: fix: Add task screen color/theme doesnot follow dark theme mode
## Description:
In the 'add task' screen, the window displays in colors similar to the light mode despite dark mode being active.

## Solution:
To address this, ensure a consistent theme or define a specific color theme for the widget. This can be done by choosing a color that complements the overall background of the app.

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by its-me-abhishek**
# Description

Fixed the issue of inconsistency of theme colors on add task screen.

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by its-me-abhishek** [comment]
@Pavel401 Please review my PR

**Comment by Pavel401** [comment]
Hey, I saw the changes you have made.

Screenshot_1700124928

 The color scheme of the dialog doesn't seem to align with the overall theme. Additionally, the text theme appears to be somewhat inaccurate. In the provided screenshot, it's evident that the text color lacks visibility, and the dialog box color seems to overpower the UI color. I suggest exploring alternative shades to enhance the overall visual experience.


Screenshot 2023-11-16 at 2 09 47 PM

For reference, I came across an example in the [Material 3 guidelines](https://m3.material.io/components/date-pickers/specs), which showcases a more cohesive and visually appealing design. Please consider implementing a similar approach, as demonstrated in the attached image.

**Comment by Pavel401** [comment]
@its-me-abhishek Also make sure there are no errors during CI/CD.

**Comment by its-me-abhishek** [comment]
I have updated these and fixed the CI/CD issues

**Pull request merged**
