### PR TITLE
loading screen bug fixed, by giving permissions

### LINKED ISSUE #368: Changing Data Directory Not Working
### Describe your issue

When trying to change directory in settings, the directory change never finishes and just infinitely loops on "Moving data to new directory"

### Steps to reproduce

1. Menu > Settings > Change directory
2. Select directory
3. Change never completes

### What was the expected result?

Directory changes

### Put here any screenshots or videos (optional)

_No response_

### How can we contact you (optional)

_No response_

### Would you like to work on this issue?

No

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

### PR DESCRIPTION
**Pull request by Shubham04Jha**
# Description

Solved loading screen bug by giving necessary permissions.

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by BrawlerXull** [comment]
LGTM!
Can you fix other Bugs related to Base Director too on the setting page where the base directory text is not being changed according to the setting applied by the user?
Also can you make the permissions logic more abstract?

**Comment by BrawlerXull** [comment]
LGTM 👏 
@Pavel401 please review

**Comment by Pavel401** [comment]
@BrawlerXull The CI flow is broken

**Comment by BrawlerXull** [comment]
As [per](https://arc.net/l/quote/ohwrsfmv) I guess it is because of `GitHub deprecating versions v1 and v2 of the actions/upload-artifact action`
well I'll fix it

**Review by BrawlerXull — APPROVED** [review]
LGTM tried to build the apk and it worked fine in my local device both the notification and storage service works fine!

**Comment by BrawlerXull** [comment]
LGTM tried to build the apk and it worked fine in my local device both the notification and storage service works fine! 
Merging it!

**Pull request merged**
