### PR TITLE
Added Swipe Functionality to Pending Tasks

### PR DESCRIPTION
**Pull request by Om-Gujarathi**
Pending Tasks are now Slidable as explained in Issue #59 

- Swipe left to Delete the Task
- Swipe Right to Complete the Task.

### CODE REVIEW

**Comment by NishantSinghal19** [comment]
is there any undo button appear after doing this or like that save window?

**Comment by NishantSinghal19** [comment]
I think that will be the problem with slidables

**Comment by Om-Gujarathi** [comment]
> is there any undo button appear after doing this or like that save window?

Yes, Now I have Added the Requested Changes.
A Save window will appear to confirm the modified task.

**Review by NishantSinghal19 — APPROVED** [review]
Now it is right

**Pull request merged**
