### PR TITLE
Add task feature when the task is added

### LINKED ISSUE #251: Enhancing App Functionality with Tag Feature
### Describe your improvement idea or feature request

Considering improvements for our app, I propose the addition of a tag feature during the creation process. This would include incorporating default tags such as 'school,' 'housework,' 'office,' etc. This enhancement aims to streamline organization and categorization. I'm excited about working on this modification to make our app even better.

### How would you like to see it implemented?

I envision the implementation of the tag feature to be user-friendly and intuitive. Users could have the option to easily add tags during the app creation process or while managing their tasks. The default tags like 'school,' 'housework,' 'office,' etc., would provide a helpful starting point for organization. Additionally, a simple interface for adding, editing, and removing tags would contribute to a seamless user experience. I look forward to collaborating on this implementation to ensure it aligns with our users' needs and preferences

### Put here any screenshots or videos (optional)

_No response_

### How can we contact you (optional)

_No response_

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

### PR DESCRIPTION
**Pull request by abhisheksharma010**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #251 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Pavel401** [comment]
Screenshot_1706434508

In case there is some space in the tag, it shows this snack bar behind the dialog. We can fix that by removing the extra space from the tag.
```dart
String originalString = "  Hello, world!   ";
String trimmedString = originalString.trim();
print(trimmedString); // Output: "Hello, world!"
```
Also, add a plus icon on the tag field and chip view so that the user can add multiple tags and remove the space on Click.

**Comment by Pavel401** [comment]
@abhisheksharma010 Maybe we could add some user preferences in the settings, allowing users to toggle the feature on or off.

Include a toggle in the settings menu and provide a description of the purpose of the red border. Otherwise, first-time users may be confused.

**Comment by abhisheksharma010** [comment]
Okay, sir. Firstly, I will resolve this tag feature. Then, I will work on the toggle feature. The deadline task will take time because I have to go through files and understand how things are progressing for the task deadline

**Comment by abhisheksharma010** [comment]
Sir, I also noticed that this thing is present there. If I empty the tag and press enter, it will also add a plus sign (+0), and there is a restriction that the tag cannot contain spaces.

**Comment by abhisheksharma010** [comment]
How is it ??

**Comment by Pavel401** [comment]
Instead of the elevated button use the suffixIcon property of the tags  TextField.
Use Icon(Icons.add) as a suffixIcon.

**Review by Pavel401 — APPROVED** [review]
Cool !

**Pull request merged**
