### PR TITLE
Added 24 hr format feature

### PR DESCRIPTION
**Pull request by codesage01**
# Description

Added 24hour Choice.
Steps:
1.Click on Add Icon,
2.Click to Choose 24Hour

## Screenshots

https://github.com/CCExtractor/taskwarrior-flutter/assets/149355139/2ff0be2d-8e55-40a1-907d-ecc02dcc211e

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by codesage01** [comment]
@Pavel401,Please review this

**Review by Pavel401 — COMMENTED** [review]
Instead of displaying the option in the dialog, we can add a new toggle to enable the 24-hour format. Instead, add the toggle in the settings menu. Adding a task from the dialog should require the fewest button clicks possible. Also, make sure it's backward compatible, so cross-client usage stays the same. I mean, in the original Taskwarrior CLI, does it support 24-hour and 12-hour formats?

**Comment by codesage01** [comment]
> Instead of displaying the option in the dialog, we can add a new toggle to enable the 24-hour format. Instead, add the toggle in the settings menu. Adding a task from the dialog should require the fewest button clicks possible. Also, make sure it's backward compatible, so cross-client usage stays the same. I mean, in the original Taskwarrior CLI, does it support 24-hour and 12-hour formats?
ok, Can You give me some more time to this?

**Comment by codesage01** [comment]
Sorry, recently my mid sem exam was finished, and also i am not able to add this feature in settings toggle form. Can you please help in this?

**Comment by codesage01** [comment]
i solved this, Please open this  issue,i will make PR for this @Pavel401.

**Comment by codesage01** [comment]
https://github.com/CCExtractor/taskwarrior-flutter/assets/149355139/157760db-43d9-4e7c-b469-c9a6bd54bd4e

**Comment by codesage01** [comment]
@Pavel401 will their any change? please review it?

**Review by Pavel401 — APPROVED** [review]

**Pull request merged**
