### PR TITLE
implemeted scroll view of home widget

### PR DESCRIPTION
**Pull request by JangamRuthvik**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Pavel401** [comment]
@JangamRuthvik some checks are failing

**Comment by JangamRuthvik** [comment]
@Pavel401 yes i have modified some changes and all checks have been passed

**Comment by JangamRuthvik** [comment]
Hey @Pavel401 can you have a look at this pull request

**Comment by Pavel401** [comment]
> Hey @Pavel401 can you have a look at this pull request

Busy today ... Will check tomorrow.

**Comment by JangamRuthvik** [comment]
sure @Pavel401 take a  moment only at your convenience

**Pull request merged**
