### PR TITLE
style: UI Changes in Task Details 

### PR DESCRIPTION
**Pull request by iam-sarthak**
**Made some UI Changes on the Task Details Page** 

**Before**          |  **After**
:-------------------------:|:-------------------------:
before | after

Benefits of these changes:
- Help user to understand that a particular place is Editable
- Give a much better UI Experience to End Users.

### CODE REVIEW

**Comment by Pavel401** [comment]
@iam-sarthak create an issue before check-in your code.

**Comment by iam-sarthak** [comment]
> @iam-sarthak create an issue before check-in your code.

@Pavel401  Please, check #80

**Comment by NishantSinghal19** [comment]
It is not looking so good

**Comment by NishantSinghal19** [comment]
Not needed

**Pull request closed without merging**
