### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Sabra-xD**
# Description

A notifier needed to be displayed for the user in a snackBar.
Wrapped the AlertDialog of add_Task with a Scaffold, so the snackBar's ScaffoldMessanger can locate it and displayed the message.
Also, highlighted the due time to be in red when the time selected is in the past.

AlertDialog is being displayed if the user haven't set up a TaskServer.

## Screenshots
Screenshot_2024-02-23-07-59-30-60_9bdaab249332ff0aa81548d24e981681

Screenshot_2024-02-25-01-56-21-82_9bdaab249332ff0aa81548d24e981681

overflow

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Sabra-xD** [comment]
Hey, @Pavel401 I remove the flushBar from earlier since it caused and issue with adding the task, it didn't close it if the flush bar was still on screen for its 2 seconds, and I just made do with the snackBar instead.

**Comment by Pavel401** [comment]
Hi @Sabra-xD, thank you for submitting the PR. By the way, could you replace the dialog with a snack bar on the task server page? In most places, we use Snackbar throughout the app, so it would be great if the new one matched. Also, please make sure that the snack bar matches the theme of the app, both in dark and light mode. Thank you!

**Comment by Sabra-xD** [comment]
@Pavel401 Done.

**Comment by Sabra-xD** [comment]
Hey @Pavel401 I have added the solution for the most recent issue to the PR.

**Review by Pavel401 — APPROVED** [review]

**Comment by Pavel401** [comment]
From next time please send multiple PRs for each issue. @Sabra-xD

**Pull request merged**
