### PR TITLE
Fixed #38

### LINKED ISSUE #38: Add task -- Better UX
image

Here instead of null in due, an icon of clock would be a nice add on to UX

### PR DESCRIPTION
**Pull request by MarkisDev**
- Added clock icon for better user experience
- Added padding to "Due:" to align with the button
- Formatted date to dd/mm/yy and  time to hh:mm AM/PM for better user experience

### CODE REVIEW

**Comment by MarkisDev** [comment]
Adding pics to show the UI after the change
qemu-system-x86_64_0wFZtP7QaI
qemu-system-x86_64_a4YhBR3O2T

**Comment by NishantSinghal19** [comment]
It is not looking Good as I want to show null when nothing is there

**Comment by MarkisDev** [comment]
Hey, maybe instead of the icon, we could show something more user friendly?
Not everyone knows programming, null might not make sense to them

Also, what about the date formats?
It's much more readable compared to an ISO8601 string?

**Comment by NishantSinghal19** [comment]
The date format is already fixed, and what replacement of null you are suggesting?

**Comment by MarkisDev** [comment]
Hey, attaching a preview of a better string instead of null.
With regards to date format, I've removed the dependency on Jiffy (seemed unnecessary since we already have intl)
qemu-system-x86_64_4mCwPn4KW1
qemu-system-x86_64_0wFZtP7QaI

Please let me know what you think!

**Comment by NishantSinghal19** [comment]
So you have did changes in your pull request

**Comment by MarkisDev** [comment]
The PR was closed, I'll add the changed right now!

**Pull request closed without merging**
