### PR TITLE
refactor: redesigned home screen widget for android

### LINKED ISSUE #415: UI: a Way Better Widget - mockup
### Describe your improvement idea or feature request

It's great that there's a widget.. sadly.. it's a terrible widget! 

A good widget should;
- be able to share the screen with other icons (this one's huge!)
- follow the app color theme (this one come in light theme only)
- follow the app filter and sort (this one ignores filters and sorts on ID only)
- show as many tasks as practical
- feature an Add Task button

Here's a mockup of what I think would be a much better widget!

### How would you like to see it implemented?

widget gets a workover.. unfortunately, I don't know how to do that :-)

### Put here any screenshots or videos (optional)

better_widget

### How can we contact you (optional)

_No response_

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

### PR DESCRIPTION
**Pull request by SGI-CAPP-AT2**
# Description
This issue fixes issue #415,
As per Issue this PR refactors the Home Screen widget with new features and some design changes.
## Fixes #415

Now smallest size is 2x2 cells

> follow the app color theme (this one come in light theme only)

It follows App Color Theme Instead of System Theme

> follow the app filter and sort (this one ignores filters and sorts on ID only)

Updates on filter change occurs

> show as many tasks as practical

at smallest 3x2 size it can show upto 4 tasks
at preferable 3x3 size it can show upto 7 tasks

> feature an Add Task button

A button added which redirects to add dialog

closes: #415 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots
|DARK MODE|LIGHT MODE|
|---|---|
| DARK MODE | LIGHT MODE |

https://github.com/user-attachments/assets/4121d9c8-1065-4001-aa6c-a8a60675bc7c

https://github.com/user-attachments/assets/4829ab65-38c5-4bfe-81d2-dc2a22f0abdd

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by SGI-CAPP-AT2** [comment]
@Pavel401 The PR is Ready to Review.

**Comment by SGI-CAPP-AT2** [comment]
also https://github.com/CCExtractor/taskwarrior-flutter/pull/402#issuecomment-2556280609 ,
These changes are added by this PR
#402 and #417 Both PRs are Independent from Each other because This PR uses Android HomeScreen widgets approach in order to change theme mode explicitly as per application theme mode.

**Comment by linuxcaffe** [comment]
@SGI-CAPP-AT2 Brilliant!

**Comment by BrawlerXull** [comment]
the design lgtm 
@Pavel401 what's your take on it?

**Comment by linuxcaffe** [comment]
@BrawlerXull out of curiosity.. what's lgtm?

**Comment by BrawlerXull** [comment]
> @BrawlerXull out of curiosity.. what's lgtm?

It's `Looks good to me` :)

**Comment by Pavel401** [comment]
@SGI-CAPP-AT2 Does it support the iOS widget as well?

**Comment by SGI-CAPP-AT2** [comment]
@Pavel401 ,
No it doesn't, also I don't have env to test on iOS

**Review by Pavel401 — APPROVED** [review]

**Pull request merged**
