### PR TITLE
UI improvement for Add profile button

### PR DESCRIPTION
**Pull request by bhav-khurana**
Minor UI improvement for the Add new profile button on the profiles page
#12  UI improvement

It now looks like this

WhatsApp Image 2022-10-01 at 23 26 22

### CODE REVIEW

**Comment by NishantSinghal19** [comment]
It is looking bad in  my opinion can you do it somewhere else

**Comment by bhav-khurana** [comment]
Can we add this add profile button in the app bar?

**Comment by bhav-khurana** [comment]
@NishantSinghal19 sir is this fine?

**Comment by NishantSinghal19** [comment]
Yes looking good

**Comment by bhav-khurana** [comment]
@NishantSinghal19 Sir actually I hadn't commited these changes yet😅 i was just asking if it was looking fine...can u please reopen the PR so that I can commit these changes

**Comment by NishantSinghal19** [comment]
Bro make a new pr i will make this invalid

**Comment by bhav-khurana** [comment]
> Bro make a new pr i will make this invalid 

I have made the new PR

**Pull request merged**
