### PR TITLE
Turned on auto focus in homepage searchbar

### PR DESCRIPTION
**Pull request by BrawlerXull**
# Description

Turned the auto focus on when search icon is clicked

## Fixes #(issue_no)

Don't fixed any issues - UI Developement

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

### CODE REVIEW

**Comment by Pavel401** [comment]
Please make sure to create an issue before submitting a pull request (PR).

**Comment by BrawlerXull** [comment]
> Please make sure to create an issue before submitting a pull request (PR).

I'll take care of that from next time :)

**Comment by Pavel401** [comment]
@BrawlerXull, please ensure that your code passes the CI and also create an issue with the PR description.

**Comment by BrawlerXull** [comment]
I'll look into it 👍

**Pull request merged**
